export enum TaskType {
  ESSAY = 'ESSAY',
  CODE = 'CODE',
  INTEGER = 'INTEGER',
  FLAG = 'FLAG',
  MULTIPLE_CHOICE_SELECT_ONE = 'MULTIPLE_CHOICE_SELECT_ONE',
  MULTIPLE_CHOICE_SELECT_SEVERAL = 'MULTIPLE_CHOICE_SELECT_SEVERAL',
  RAW_HANDWRITING = 'RAW_HANDWRITING',
  PROCESSED_HANDWRITING = 'PROCESSED_HANDWRITING',
}
