# Basically dev.local.docker-compose.yml, but with postgres
services:
  backend:
    extends:
      file: dev.local.docker-compose.yml
      service: backend
    environment:
      - DB_URL=postgresql://user:pass@db/answerbook
  
  frontend:
    extends:
      file: dev.local.docker-compose.yml
      service: frontend
  
  # add db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: answerbook
    volumes:
      - answerbook-api-pgdata:/var/lib/postgresql/data

volumes:
  answerbook-api-pgdata:
